default:
  image: docker:latest
  services:
    - docker:dind

variables:
  project_name: MyProjectName
  SEMANTIC_RELEASE_PACKAGE: ${project_name}

stages:
  - build
  - release

build-supplementary-image:
  stage: build
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/ujlbu4/gitlab-semantic-release .
    - docker push registry.gitlab.com/ujlbu4/gitlab-semantic-release

release:
  image: node:12-slim
  stage: release
  variables:
    IMAGE_NAME: registry.gitlab.com/ujlbu4/gitlab-semantic-release
  script:
    - env
    - npx semantic-release
  only:
    - master
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/
