default:
  image: docker:latest
  services:
    - docker:dind

variables:
  project_name: MyProjectName
  SEMANTIC_RELEASE_PACKAGE: ${project_name}

stages:
  - build
  - release

build-supplementary-image:
  stage: build
  script:
    - docker login registry.gitlab.com -u mlonn -p ${GITLAB_TOKEN}
    - docker pull registry.gitlab.com/mlonn/gitlab-semantic-release
    - docker build -t registry.gitlab.com/mlonn/gitlab-semantic-release .
    - docker push registry.gitlab.com/mlonn/gitlab-semantic-release
  only:
    - master
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/

demo:
  stage: build
  script:
    - echo "demo"

release:
  image: registry.gitlab.com/mlonn/gitlab-semantic-release
  stage: release
  script:
    - env
    - npx semantic-release
  only:
    - master
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/
